# figure
out_folder= 'img'
out_name= 'informationScore'
title= 'debug information score (eps=1e-1)'
dpi= 300

# true labels (same root folder)
true_data = '20240115-105053_output'

# model label= predicitonFiles in root_folder (without .pt)
root_folder= 'computed'
[model_defs]
'rand. class.'= 'randomClassifier/240120-204802'
'always correct'= 'randomClassifier/correct'
'always incorrect'= 'randomClassifier/incorrect'
'always useful'= 'randomClassifier/useful'
'always misleading'= 'randomClassifier/misleading'

