# figure
out_folder= 'img'
out_name= 'tuningSGC'
title= 'SGC 1 layer: aggr. (depth)'
dpi= 300

# true labels (same root folder)
true_data = '20240115-105053_output'

# model label= predicitonFiles in root_folder (without .pt)
root_folder= 'computed'
[model_defs]
'rand. class.'= 'randomClassifier/240120-204802'
#'trad. ML'= 'traditionalML_20240115-181619'#
'max (1)'= 'SimpleGC/240121-150446'
#'max (2)'= 'SimpleGC/240121-152246'
#'max (3)'= 'SimpleGC/240121-153403'
'mean (1)'= 'SimpleGC/240121-162647'
#'mean (2)'= 'SimpleGC/240121-163840'
#'mean (3)'= 'SimpleGC/240121-165033'
'min (1)'= 'SimpleGC/240121-170655'
#'min (2)'= 'SimpleGC/240121-171308'
#'min (3)'= 'SimpleGC/240121-171632'
#'mul (1)'= 'SimpleGC/240121-173405'
#'mul (2)'= 'SimpleGC/240121-174619'
#'mul (3)'= 'SimpleGC/240121-181706'

