# figure
out_folder= 'img'
out_name= 'embedMLP'
title= 'DeepWalk (d.32) MLP embed / hdim.opt '
dpi= 300

# true labels (same root folder)
true_data = '20240115-105053_output'

# model label= predicitonFiles in root_folder (without .pt)
root_folder= 'computed'
[model_defs]
'rand. class.'= 'randomClassifier/240120-204802'
'5-20 / 0.adam'= 'embeddingMLP/240122-161735'
'5-20 / 0.sgd'= 'embeddingMLP/240122-162601'
'10-20 / 0.adam'= 'embeddingMLP/240122-150155'
'10-20 / 0.sgd'= 'embeddingMLP/240122-151034'
'16-20 / 0.adam'= 'embeddingMLP/240122-151913'
'16-20 / 0.sgd'= 'embeddingMLP/240122-152742'

