# figure
out_folder= 'img'
out_name= 'informationScore'
title= 'debug information score (eps=1e-1)'

# true labels (same root folder)
true_data = '20240115-105053_output'

# model label= predicitonFiles in root_folder (without .pt)
root_folder= 'computed'
[model_defs]
'rand. class.'= 'randomClassifier/240120-204802'
'always correct'= 'randomClassifier/correct'
'always incorrect'= 'randomClassifier/incorrect'
'always useful'= 'randomClassifier/useful'
'always misleading'= 'randomClassifier/misleading'
#'trad. ML'= 'traditionalML_20240115-181619'#
#'k:1 hdim. 5'= 'SimpleGC/240119-111229'
#'k:2/0 hdim. 5'= 'SimpleGC/240119-111240'#
#'k:1/1 hdim. 2'= 'SimpleGC/240119-225259'
#'k:1/1 hdim. 3 false'= 'SimpleGC/240119-232054'#
#'k:1/1 hdim. 3 true'= 'SimpleGC/240119-235447'
#'k:1/1 hdim. 4 '= 'SimpleGC/240120-003337'
#'k:1/1 hdim. 5 '= 'SimpleGC/240120-011425'
#'k:1/1 hdim. 7 '= 'SimpleGC/240120-110455'
#'k:1/1 hdim. 10 '= 'SimpleGC/240120-111816'#
#'k:1/1 hdim. 12 '= 'SimpleGC/240120-112925'
#'k:1/1 hdim. 14 '= 'SimpleGC/240120-110719'
#'k:1/1 hdim. 12 '= 'SimpleGC/240120-153025'#
#'fix info score'= 'SimpleGC/240120-194323'

