# job handling
save= true
out_folder= 'GraphSAGE'
device= 'cuda'
num_jobs= 1 

# dataset
root_folder= 'computed'
input_name= '20240115-105053'
seed_name= 'seedSequence_p10'

# model 
batch_size= 10
# layer 1
conv1.aggr= 'mean' # sum mean(d) min max mul
conv1.dropout= 0.2
conv1.activation= true
# layer 2
conv2.hidden_dim= 1000 # 0 deactivated
conv2.aggr= 'mean' # sum mean(d) min max mul
conv2.dropout= 0.2
conv2.activation= false

# optimizer Adam or SGD 
opt.name= 'sgd' # case insensitive
#opt.learning_rate= 5e-3 # Adam
opt.learning_rate= 1e-1 # SGD
opt.weight_decay= 1e-8 # Adam, SGD
opt.nesterov= false # SGD
opt.momentum= 0.1 # SGD
opt.dampening= 0 # SGD

# training
test_share= 0.3
max_epochs= 300
# early stopping
ma_window= 50
ma_threshold= 2e-3
