# job handling
save= true
out_folder= 'GraphSAGE'
device= 'cuda'
num_jobs= 1
seed_name= 'seedSequence_p10'

# dataset
root_folder= 'computed'
input_name= '20240115-105053'

# model 
batch_size= 10
# layer 1
hidden_dim= 3
conv1_activation= true
# layer 2
conv2_switch= true
conv2_activation= true

# optimizer
learning_rate= 1e-2
weight_decay= 5e-4

# trainig
test_share= 0.3
max_epochs= 300
ma_window= 100
ma_threshold= 1e-3
